### ISSUE TITLE
第一次下载运行

### ISSUE THREAD

**Issue by WalkonJoey** [JpressProjects/jpress#24]
按照说明文档上说的在maven打包的时候出现问题，出现问题：

```
E:\E Jpress Workspace\jpress\jpress-web>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jpress-web 1.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.jpress:jpress-utils:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-db-api:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-db-mysql:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-oauth2:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-message:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-search-api:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-search-dbsimple:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-consts:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-model:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-web-core:jar:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-web-template-jblog:war:1.0 is missing, no dependency information available
[WARNING] The POM for io.jpress:jpress-web-template-the3:war:1.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.636 s
[INFO] Finished at: 2016-09-13T12:55:21+08:00
[INFO] Final Memory: 7M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jpress-web: Could not resolve dependencies for project io.jpress:jpress-web:war:1.0: The following artifacts could not be resolved: io.jpress:jpress-utils:jar:1.0, io.jpress:jpress-db-api:jar:1.0, io.jpress:jpress-db-mysql:jar:1.0, io.jpress:jpress-oauth2:jar:1.0, io.jpress:jpress-message:jar:1.0, io.jpress:jpress-search-api:jar:1.0, io.jpress:jpress-search-dbsimple:jar:1.0, io.jpress:jpress-consts:jar:1.0, io.jpress:jpress-model:jar:1.0, io.jpress:jpress-web-core:jar:1.0, io.jpress:jpress-web-template-jblog:war:1.0, io.jpress:jpress-web-template-the3:war:1.0: Failure to find io.jpress:jpress-utils:jar:1.0 in http://uk.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of UK has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

然后将项目在eclipse中打开，tomcat:run正常，但是访问http://localhost:8080/jpress-web/install报500错误，后台报nullpointexception,如下：

```
2016-09-13 12:24:04
[ERROR]-[Thread: http-8080-1]-[com.jfinal.core.ActionHandler.handle()]: /install
java.lang.NullPointerException
    at io.jpress.model.core.JModel.getTableName(JModel.java:164)
    at io.jpress.model.core.JModel.createSelectSql(JModel.java:55)
    at io.jpress.model.core.JModel.createSelectWhereSql(JModel.java:63)
    at io.jpress.model.core.JModel.doFindFirst(JModel.java:95)
    at io.jpress.model.query.OptionQuery$1.load(OptionQuery.java:37)
    at com.jfinal.plugin.ehcache.CacheKit.get(CacheKit.java:85)
    at io.jpress.model.query.OptionQuery.findValue(OptionQuery.java:34)
    at io.jpress.front.controller.IndexController.setGlobleAttrs(IndexController.java:83)
    at io.jpress.front.controller.IndexController.doRender(IndexController.java:47)
    at io.jpress.front.controller.IndexController.index(IndexController.java:39)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
    at io.jpress.core.interceptor.HookInterceptor.intercept(HookInterceptor.java:34)
    at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
    at io.jpress.interceptor.AdminInterceptor.intercept(AdminInterceptor.java:36)
    at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
    at io.jpress.interceptor.GlobelInterceptor.intercept(GlobelInterceptor.java:33)
    at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
    at io.jpress.core.interceptor.JI18nInterceptor.intercept(JI18nInterceptor.java:48)
    at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
    at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
    at io.jpress.core.MyDruidStatViewHandler.handle(MyDruidStatViewHandler.java:43)
    at io.jpress.core.cache.ActionCacheHandler.handle(ActionCacheHandler.java:84)
    at io.jpress.core.JHandler.handle(JHandler.java:81)
    at io.jpress.core.cache.ActionCacheHandler.handle(ActionCacheHandler.java:84)
    at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
```

**Comment by baoguok** [comment]
直接jpress目录下打包即可

**Comment by nzsghdx** [comment]
大佬是怎么解决的,同样问题.
