### ISSUE TITLE
大家运行后有没有不能使用数据库的问题，具体如下

### ISSUE THREAD

**Issue by ITGrub** [JpressProjects/jpress#59]
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=55694:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/xingxing/Downloads/jpress-master-2/target/classes:/Users/xingxing/maven/maven_repo/io/jboot/jboot/1.0-beta5/jboot-1.0-beta5.jar:/Users/xingxing/maven/maven_repo/com/jfinal/cos/2017.5/cos-2017.5.jar:/Users/xingxing/maven/maven_repo/com/jfinal/jfinal-weixin/1.9/jfinal-weixin-1.9.jar:/Users/xingxing/maven/maven_repo/com/zaxxer/HikariCP/2.6.3/HikariCP-2.6.3.jar:/Users/xingxing/maven/maven_repo/mysql/mysql-connector-java/5.1.42/mysql-connector-java-5.1.42.jar:/Users/xingxing/maven/maven_repo/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/xingxing/maven/maven_repo/io/undertow/undertow-core/1.4.18.Final/undertow-core-1.4.18.Final.jar:/Users/xingxing/maven/maven_repo/org/jboss/logging/jboss-logging/3.2.1.Final/jboss-logging-3.2.1.Final.jar:/Users/xingxing/maven/maven_repo/org/jboss/xnio/xnio-api/3.3.8.Final/xnio-api-3.3.8.Final.jar:/Users/xingxing/maven/maven_repo/org/jboss/xnio/xnio-nio/3.3.8.Final/xnio-nio-3.3.8.Final.jar:/Users/xingxing/maven/maven_repo/io/undertow/undertow-servlet/1.4.18.Final/undertow-servlet-1.4.18.Final.jar:/Users/xingxing/maven/maven_repo/org/jboss/spec/javax/servlet/jboss-servlet-api_3.1_spec/1.0.0.Final/jboss-servlet-api_3.1_spec-1.0.0.Final.jar:/Users/xingxing/maven/maven_repo/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/Users/xingxing/maven/maven_repo/com/weibo/motan-core/0.3.1/motan-core-0.3.1.jar:/Users/xingxing/maven/maven_repo/commons-pool/commons-pool/1.6/commons-pool-1.6.jar:/Users/xingxing/maven/maven_repo/com/codahale/metrics/metrics-core/3.0.1/metrics-core-3.0.1.jar:/Users/xingxing/maven/maven_repo/com/google/guava/guava/18.0/guava-18.0.jar:/Users/xingxing/maven/maven_repo/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar:/Users/xingxing/maven/maven_repo/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/xingxing/maven/maven_repo/commons-codec/commons-codec/1.4/commons-codec-1.4.jar:/Users/xingxing/maven/maven_repo/com/weibo/motan-transport-netty/0.3.1/motan-transport-netty-0.3.1.jar:/Users/xingxing/maven/maven_repo/org/jboss/netty/netty/3.2.5.Final/netty-3.2.5.Final.jar:/Users/xingxing/maven/maven_repo/com/weibo/motan-registry-consul/0.3.1/motan-registry-consul-0.3.1.jar:/Users/xingxing/maven/maven_repo/com/ecwid/consul/consul-api/1.2.1/consul-api-1.2.1.jar:/Users/xingxing/maven/maven_repo/com/google/code/gson/gson/2.3/gson-2.3.jar:/Users/xingxing/maven/maven_repo/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar:/Users/xingxing/maven/maven_repo/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/xingxing/maven/maven_repo/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/xingxing/maven/maven_repo/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/xingxing/maven/maven_repo/com/alibaba/fastjson/1.2.36/fastjson-1.2.36.jar:/Users/xingxing/maven/maven_repo/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/Users/xingxing/maven/maven_repo/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/Users/xingxing/maven/maven_repo/de/ruedigermoeller/fst/2.52/fst-2.52.jar:/Users/xingxing/maven/maven_repo/com/fasterxml/jackson/core/jackson-core/2.8.8/jackson-core-2.8.8.jar:/Users/xingxing/maven/maven_repo/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar:/Users/xingxing/maven/maven_repo/org/objenesis/objenesis/2.5.1/objenesis-2.5.1.jar:/Users/xingxing/maven/maven_repo/org/jsoup/jsoup/1.10.3/jsoup-1.10.3.jar:/Users/xingxing/maven/maven_repo/net/sf/ehcache/ehcache/2.10.4/ehcache-2.10.4.jar:/Users/xingxing/maven/maven_repo/com/netflix/hystrix/hystrix-core/1.5.12/hystrix-core-1.5.12.jar:/Users/xingxing/maven/maven_repo/com/netflix/archaius/archaius-core/0.4.1/archaius-core-0.4.1.jar:/Users/xingxing/maven/maven_repo/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar:/Users/xingxing/maven/maven_repo/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/xingxing/maven/maven_repo/io/reactivex/rxjava/1.2.0/rxjava-1.2.0.jar:/Users/xingxing/maven/maven_repo/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar:/Users/xingxing/maven/maven_repo/com/netflix/hystrix/hystrix-metrics-event-stream/1.5.12/hystrix-metrics-event-stream-1.5.12.jar:/Users/xingxing/maven/maven_repo/com/netflix/hystrix/hystrix-serialization/1.5.12/hystrix-serialization-1.5.12.jar:/Users/xingxing/maven/maven_repo/com/fasterxml/jackson/module/jackson-module-afterburner/2.7.5/jackson-module-afterburner-2.7.5.jar:/Users/xingxing/maven/maven_repo/com/fasterxml/jackson/core/jackson-annotations/2.7.5/jackson-annotations-2.7.5.jar:/Users/xingxing/maven/maven_repo/com/netflix/hystrix/hystrix-codahale-metrics-publisher/1.5.12/hystrix-codahale-metrics-publisher-1.5.12.jar:/Users/xingxing/maven/maven_repo/io/dropwizard/metrics/metrics-core/3.2.2/metrics-core-3.2.2.jar:/Users/xingxing/maven/maven_repo/io/dropwizard/metrics/metrics-servlets/3.2.2/metrics-servlets-3.2.2.jar:/Users/xingxing/maven/maven_repo/io/dropwizard/metrics/metrics-healthchecks/3.2.2/metrics-healthchecks-3.2.2.jar:/Users/xingxing/maven/maven_repo/io/dropwizard/metrics/metrics-json/3.2.2/metrics-json-3.2.2.jar:/Users/xingxing/maven/maven_repo/io/dropwizard/metrics/metrics-jvm/3.2.2/metrics-jvm-3.2.2.jar:/Users/xingxing/maven/maven_repo/com/papertrail/profiler/1.0.2/profiler-1.0.2.jar:/Users/xingxing/maven/maven_repo/joda-time/joda-time/2.9.1/joda-time-2.9.1.jar:/Users/xingxing/maven/maven_repo/com/fasterxml/jackson/core/jackson-databind/2.6.6/jackson-databind-2.6.6.jar:/Users/xingxing/maven/maven_repo/com/google/inject/guice/4.1.0/guice-4.1.0.jar:/Users/xingxing/maven/maven_repo/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/xingxing/maven/maven_repo/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/xingxing/maven/maven_repo/org/apache/shiro/shiro-core/1.3.2/shiro-core-1.3.2.jar:/Users/xingxing/maven/maven_repo/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar:/Users/xingxing/maven/maven_repo/org/apache/shiro/shiro-web/1.3.2/shiro-web-1.3.2.jar:/Users/xingxing/maven/maven_repo/cglib/cglib-nodep/3.2.5/cglib-nodep-3.2.5.jar:/Users/xingxing/maven/maven_repo/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar:/Users/xingxing/maven/maven_repo/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar io.jpress.Starter
objc[1685]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x10b4614c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10b53d4e0). One of the two will be used. Which one is undefined.
  ____  ____    ___    ___   ______ 
 |    ||    \  /   \  /   \ |      |
 |__  ||  o  )|     ||     ||      |
 __|  ||     ||  O  ||  O  ||_|  |_|
/  |  ||  O  ||     ||     |  |  |  
\  `  ||     ||     ||     |  |  |  
 \____||_____| \___/  \___/   |__|  
                                    
JbootConfig {mode='dev', bannerEnable='true', bannerFile='banner.txt', cron4jEnable='true', cron4jFile='cron4j.properties', jfinalConfig='io.jboot.web.JbootAppConfig', serializer='fst2'}
JbootServerConfig {type='undertow', host='0.0.0.0', port='8090', contextPath='/'}
2017-08-16 15:08:34.067 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2017-08-16 15:08:37.135 INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
Can not create Table object, maybe the table mapping is not exists.
2017-08-16 15:08:37.270 ERROR com.jfinal.core.Config - Plugin start error: com.jfinal.plugin.activerecord.ActiveRecordPlugin. 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:55)
	at com.jfinal.plugin.activerecord.ActiveRecordPlugin.start(ActiveRecordPlugin.java:226)
	at com.jfinal.core.Config.startPlugins(Config.java:107)
	at com.jfinal.core.Config.configJFinal(Config.java:53)
	at com.jfinal.core.JFinal.init(JFinal.java:63)
	at com.jfinal.core.JFinalFilter.init(JFinalFilter.java:49)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:571)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
	at io.jboot.server.undertow.UnderTowServer.initUndertowServer(UnderTowServer.java:89)
	at io.jboot.server.undertow.UnderTowServer.start(UnderTowServer.java:202)
	at io.jboot.Jboot.startServer(Jboot.java:170)
	at io.jboot.Jboot.start(Jboot.java:142)
	at io.jboot.Jboot.run(Jboot.java:88)
	at io.jpress.Starter.main(Starter.java:11)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:108)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at com.jfinal.plugin.activerecord.TableBuilder.doBuild(TableBuilder.java:71)
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:47)
	... 18 common frames omitted
java.lang.RuntimeException: Plugin start error: com.jfinal.plugin.activerecord.ActiveRecordPlugin. 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
	at com.jfinal.core.Config.startPlugins(Config.java:116)
	at com.jfinal.core.Config.configJFinal(Config.java:53)
	at com.jfinal.core.JFinal.init(JFinal.java:63)
	at com.jfinal.core.JFinalFilter.init(JFinalFilter.java:49)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:80)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:571)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
	at io.jboot.server.undertow.UnderTowServer.initUndertowServer(UnderTowServer.java:89)
	at io.jboot.server.undertow.UnderTowServer.start(UnderTowServer.java:202)
	at io.jboot.Jboot.startServer(Jboot.java:170)
	at io.jboot.Jboot.start(Jboot.java:142)
	at io.jboot.Jboot.run(Jboot.java:88)
	at io.jpress.Starter.main(Starter.java:11)
Caused by: com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:55)
	at com.jfinal.plugin.activerecord.ActiveRecordPlugin.start(ActiveRecordPlugin.java:226)
	at com.jfinal.core.Config.startPlugins(Config.java:107)
	... 16 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.mapping' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:108)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at com.jfinal.plugin.activerecord.TableBuilder.doBuild(TableBuilder.java:71)
	at com.jfinal.plugin.activerecord.TableBuilder.build(TableBuilder.java:47)
	... 18 more
八月 16, 2017 3:08:37 下午 io.jboot.server.undertow.UnderTowServer error
严重: java.lang.IllegalArgumentException: UT000008: Handler cannot be null
java.lang.IllegalArgumentException: UT000008: Handler cannot be null
	at io.undertow.Handlers.handlerNotNull(Handlers.java:583)
	at io.undertow.server.handlers.PathHandler.addPrefixPath(PathHandler.java:131)
	at io.jboot.server.undertow.UnderTowServer.initUndertowServer(UnderTowServer.java:97)
	at io.jboot.server.undertow.UnderTowServer.start(UnderTowServer.java:202)
	at io.jboot.Jboot.startServer(Jboot.java:170)
	at io.jboot.Jboot.start(Jboot.java:142)
	at io.jboot.Jboot.run(Jboot.java:88)
	at io.jpress.Starter.main(Starter.java:11)

Exception in thread "main" java.lang.NullPointerException
	at io.jboot.server.undertow.UnderTowServer.stop(UnderTowServer.java:228)
	at io.jboot.server.undertow.UnderTowServer.start(UnderTowServer.java:206)
	at io.jboot.Jboot.startServer(Jboot.java:170)
	at io.jboot.Jboot.start(Jboot.java:142)
	at io.jboot.Jboot.run(Jboot.java:88)
	at io.jpress.Starter.main(Starter.java:11)

Process finished with exit code 1

**Comment by linzuk** [comment]
Got that as well. the fucking author doesn't update document.

**Comment by daringyun** [comment]
自己执行sql建表
